### PR TITLE
Participants

### LINKED ISSUE #9: Add filters for cities and colleges in participant viewing section.

### PR DESCRIPTION
**Pull request by ydidwania**
Addded Filter and Display  of City  and Colleges in Participant Viewing Section.
Fixed #9

### CODE REVIEW

**Comment by ydidwania** [comment]
Also added .gitignore

**Comment by TheFlash98** [comment]
Why are there so many file changes but just 19 additions and 2 deletions? 😮

**Comment by ydidwania** [comment]
Because i added a .gitignore . So the files changed are actually .pyc files which have been untracked

**Comment by sahil00199** [comment]
@ydidwania there are so many merge conflicts...how to resolve them??

**Comment by TheFlash98** [comment]
I think @ydidwania should make the PR again

**Pull request closed without merging**
